swagger: "2.0"
info:
  version: "1.0.0"
  title: "Example API"
  description: "This is an example API for demonstration purposes."
host: "example.com"
basePath: "/api"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /users:
    get:
      tags:
        - "Users"
      summary: "Get all users"
      description: "Returns a list of all users."
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
  /users/{id}:
    get:
      tags:
        - "Users"
      summary: "Get a user by ID"
      description: "Returns a single user by ID."
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the user to retrieve"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/User"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"